baseurl = "/"
languageCode = "en-US"
title = "Gina Carrion"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "gmc.jpg"
  author = "Gina Carrion"
  description = "website description"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "gmcarrion"

## Main Menu
[[menu.main]]
  name = "Writing Samples"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "rstudio projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"